# DigitalOcean App Platform Configuration
name: bazaarGuru-telegram-bot
services:
- name: web
  source_dir: /
  github:
    repo: Andrey7823/bazaarGuru-telegram-bot
    branch: main
    deploy_on_push: true
  run_command: npm start
  build_command: npm run build
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  routes:
  - path: /
  health_check:
    http_path: /health
    initial_delay_seconds: 30
    period_seconds: 10
    timeout_seconds: 5
    success_threshold: 1
    failure_threshold: 3
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "8080"
  - key: TELEGRAM_BOT_TOKEN
    value: YOUR_BOT_TOKEN_HERE
    type: SECRET
  - key: OPENAI_API_KEY
    value: YOUR_OPENAI_KEY_HERE
    type: SECRET
  - key: DATABASE_URL
    value: YOUR_DATABASE_URL_HERE
    type: SECRET
  - key: REDIS_URL
    value: YOUR_REDIS_URL_HERE
    type: SECRET
  - key: JWT_SECRET
    value: YOUR_JWT_SECRET_HERE
    type: SECRET
  - key: WEBHOOK_URL
    value: https://bazaarGuru-telegram-bot-xxxxx.ondigitalocean.app/webhook

databases:
- name: bazaarGuru-db
  engine: PG
  version: "15"
  size: db-s-1vcpu-1gb
  num_nodes: 1