# DigitalOcean App Platform Configuration
name: zabardoo-telegram-bot
services:
- name: web
  source_dir: /
  github:
    repo: Andrey71823/zabardoo-telegram-bot
    branch: main
    deploy_on_push: true
  # build only installs deps; TypeScript build не требуется для server.js
  build_command: npm install --omit=dev --legacy-peer-deps
  run_command: node server.js
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  routes:
  - path: /
  health_check:
    http_path: /health
    initial_delay_seconds: 20
    period_seconds: 10
    timeout_seconds: 5
    success_threshold: 1
    failure_threshold: 3
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "8080"
  - key: ADMIN_TOKEN
    scope: RUN_TIME
    type: SECRET

databases:
- name: zabardoo-db
  engine: PG
  version: "15"
  size: db-s-1vcpu-1gb
  num_nodes: 1